version: "3.1"

services:
  registry:
    image: registry
    environment:
      - PROXY_REMOTEURL=https://registry-1.docker.io
    # volumes: #später einfuegen

  nginx:
    image: nginx
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./cert.crt:/etc/nginx/ssl/cert.crt:ro
      - ./key.pem:/etc/nginx/ssl/key.pem:ro
    ports:
      - 443:443
